### ISSUE TITLE
Oxford English -ize and ization

### ISSUE THREAD

**Issue by philwareham** [textpattern/pophelp#24]
Since we are moving to Oxford English as our default version of English language going forward, we need to be consistent with use of -ize and -zation.

These should be used in preference to -ise and -isation, apart from for a small subset of words, [see here for more information on exempt words](http://www.oxforddictionaries.com/words/ize-ise-or-yse).

There may be a debate to be had as to whether a British English localisation uses the above or the more common -ise and -isation - both of which are valid in Britain.

[Reference on Oxford English spelling](https://en.wikipedia.org/wiki/Oxford_spelling)

**Comment by wion** [comment]
The OED is only for Textpattern's brand development. So an British English translation would be open to use '-ise', etc. Two different contexts.

**Comment by philwareham** [comment]
I am changing the use of `en-GB` as default language in Textpattern 4.7 in favour of `en` (World English), [as can be seen here](https://github.com/textpattern/textpacks/tree/master/textpacks) - and [background story here](https://github.com/textpattern/textpacks/issues/162)

Therefore as `en` will not be tied to a country specifically, I've decided it will be Oxford English as default, as is used by the ISO, UN and other international bodies - in leu of there not really being a 'World English' that everyone agrees on.

Hope that is agreeable. :)

**Comment by wion** [comment]
I don't see a problem, though any site that actually followed OE should probably use a custom `lang="en-GB-oxendict"`. So the textpattern.com site, for example. This is separate from default Txp core, which makes sense to be neutral at first.

**Comment by wion** [comment]
Language declaration is one of those things that few people give much thought to, regardless, if they're even aware of it at all.

**Comment by philwareham** [comment]
Maybe. Anyway, I don't want Australian Textpattern sites to state that they are `en-GB` language, because they are not. Don't know if that also affects country-specific SERPs but it may.

**Comment by cara-tm** [comment]
I don't understand. Do you need translations for this first and default article?

**Comment by wion** [comment]
@philwareham,

Using `en` alone is fine, of course, but if you're concern is Australia (or Canada, or South Africa, etc) then I think you're misunderstanding the point of the `en-GB-oxendict` declaration. The `en-GB` part of that is not to say you're following a country convention, but rather that the Oxford English Dictionary is a British-sourced reference, which it is. And since another one of your concerns, as stated in the head post, is being consistent about using -ise vs. -ize, the declaration puts that question to end by stating what source ends the debate. Of course, a style guide would also make that clear, but the declaration is just a way to tie all ends together.

@cara-tm,

If you're talking about translations to French, you don't have to worry about anything here. What we're talking about is words having two possible spellings (e.g. color and colour, organize and organise, etc). As far as translation goes, it's the same words, you just have to translate to the French equivalent as it's spelled in French.

**Comment by wion** [comment]
If you could write it as `en-oxendict`, that would be the ideal, but I'm doubtful that's an acceptable declaration. Don't know.

**Comment by philwareham** [comment]
Sorry, I thought I'd made it clear that 'en' will be the default pophelp/textpack base now, and that will use Oxford English rules. GB subset would use British rules (so -sation instead of -zation for example). Australia would use 'en' until such time as a specific Australian English textpack is made.

**Comment by wion** [comment]
My mistake.

**Comment by cara-tm** [comment]
@wion: Ok. Fine.
Do you project to translate this first article in the future?

**Comment by wion** [comment]
@cara-tm, at this point I don't even know what we're talking about. But, I don't plan on translating anything.

**Comment by petecooper** [comment]
>I don't understand. Do you need translations for this first and default article?

@cara-tm I referenced this issue because I spotted a typo in the default article excerpt. There is no request for translation at this time, though I do not know for certain if a future article translation is required.

**Comment by philwareham** [comment]
Done.
