### ISSUE TITLE
Pophelp needed for `remove_extra_templates`

### ISSUE THREAD

**Issue by petecooper** [textpattern/pophelp#42]
Appears as an option when exporting a template.

![screen shot 2018-01-08 at 15 49 01](https://user-images.githubusercontent.com/226578/34678722-dae9a608-f48b-11e7-9d61-4e3e5669929c.png)

**Comment by Bloke** [comment]
... or possibly not. It depends if we can find a way to handle pophelps properly from links that are made via AJAX. If you notice right now, it doesn't render the pophelp as an overlay and tries to use the old-style "new tab" popup window. This is because the AJAX handler isn't using event delegation properly so it only picks up pophelp topics that are on the page when it loads, not ones that are added afterwards during UI operation. Hopefully @bloatware has an idea about this, because I tried and failed to fix it!

If not, we'll just remove the pophelp icon for now on that link and worry about it in a future release.

**Comment by philwareham** [comment]
From my limited testing `remove_extra_templates` is potentially really dangerous and can delete a lot of files unintentionally if you don't understand what it is used for - therefore it's imperative that:

1. It absolutely has a pophelp to explain it
2. The text string wording makes it as obvious as possible that this destroys files
3. It is unchecked by default
4. Preferably an extra warning dialog is displayed prior to final confirmation of action

**Comment by Bloke** [comment]
1. Fine by me. Must be a way to get it to work. It's just JavaScript (but above my pay grade).
2. Yes. This requires some thought in that limtied space we have down there.
3. I think it should be unchecked by default _and_ retain its state once applied via a hidden user pref.
4. I think in the current multi-edit implementation, it's either ask for confirmation or not. Can't get it to double-check, as far as I know. It already asks if you're sure now.

**Comment by petecooper** [comment]
Tagging https://github.com/textpattern/textpacks/issues/249 for completeness
